# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from app import util
from app.api.models.base_model_ import Model


class InvalidUsageError(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str = None):  # noqa: E501
        """InvalidUsageError - a model defined in Swagger

        :param message: The message of this InvalidUsageError.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {"message": str}

        self.attribute_map = {"message": "message"}
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> "InvalidUsageError":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvalidUsageError of this InvalidUsageError.  # noqa: E501
        :rtype: InvalidUsageError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this InvalidUsageError.


        :return: The message of this InvalidUsageError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InvalidUsageError.


        :param message: The message of this InvalidUsageError.
        :type message: str
        """

        self._message = message
