# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from app import util
from app.api.models.base_model_ import Model
from app.api.models.latitude import Latitude  # noqa: F401,E501
from app.api.models.longitude import Longitude  # noqa: F401,E501


class Origin(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, id: int = None, latitude: Latitude = None, longitude: Longitude = None
    ):  # noqa: E501
        """Origin - a model defined in Swagger

        :param latitude: The latitude of this Origin.  # noqa: E501
        :type latitude: Latitude
        :param longitude: The longitude of this Origin.  # noqa: E501
        :type longitude: Longitude
        """
        self.swagger_types = {"id": int, "latitude": Latitude, "longitude": Longitude}

        self.attribute_map = {
            "id": "id",
            "latitude": "latitude",
            "longitude": "longitude",
        }
        self._id = id
        self._latitude = latitude
        self._longitude = longitude

    @classmethod
    def from_dict(cls, dikt) -> "Origin":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Origin of this Origin.  # noqa: E501
        :rtype: Origin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Origin.


        :return: The id of this Origin.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Origin.


        :param id: The id of this Origin.
        :type id: int
        """

        self._id = id

    @property
    def latitude(self) -> Latitude:
        """Gets the latitude of this Origin.


        :return: The latitude of this Origin.
        :rtype: Latitude
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: Latitude):
        """Sets the latitude of this Origin.


        :param latitude: The latitude of this Origin.
        :type latitude: Latitude
        """

        self._latitude = latitude

    @property
    def longitude(self) -> Longitude:
        """Gets the longitude of this Origin.


        :return: The longitude of this Origin.
        :rtype: Longitude
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: Longitude):
        """Sets the longitude of this Origin.


        :param longitude: The longitude of this Origin.
        :type longitude: Longitude
        """

        self._longitude = longitude
