# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from app import util
from app.api.models.base_model_ import Model
from app.api.models.coordinates import Coordinates  # noqa: F401,E501


class Origin(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, location: Coordinates = None):  # noqa: E501
        """Origin - a model defined in Swagger

        :param location: The location of this Origin.  # noqa: E501
        :type location: Coordinates
        """
        self.swagger_types = {"location": Coordinates}

        self.attribute_map = {"location": "location"}
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> "Origin":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Origin of this Origin.  # noqa: E501
        :rtype: Origin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def location(self) -> Coordinates:
        """Gets the location of this Origin.


        :return: The location of this Origin.
        :rtype: Coordinates
        """
        return self._location

    @location.setter
    def location(self, location: Coordinates):
        """Sets the location of this Origin.


        :param location: The location of this Origin.
        :type location: Coordinates
        """
        if location is None:
            raise ValueError(
                "Invalid value for `location`, must not be `None`"
            )  # noqa: E501

        self._location = location
