# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from app import util
from app.api.models.base_model_ import Model
from app.api.models.demand import Demand  # noqa: F401,E501


class Solution(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        demand: Demand = None,
        cluster_id: int = None,
        vehicle_id: int = None,
        stop_num: int = None,
    ):  # noqa: E501
        """Solution - a model defined in Swagger

        :param demand: The demand of this Solution.  # noqa: E501
        :type demand: Demand
        :param cluster_id: The cluster_id of this Solution.  # noqa: E501
        :type cluster_id: int
        :param vehicle_id: The vehicle_id of this Solution.  # noqa: E501
        :type vehicle_id: int
        :param stop_num: The stop_num of this Solution.  # noqa: E501
        :type stop_num: int
        """
        self.swagger_types = {
            "demand": Demand,
            "cluster_id": int,
            "vehicle_id": int,
            "stop_num": int,
        }

        self.attribute_map = {
            "demand": "demand",
            "cluster_id": "cluster_id",
            "vehicle_id": "vehicle_id",
            "stop_num": "stop_num",
        }
        self._demand = demand
        self._cluster_id = cluster_id
        self._vehicle_id = vehicle_id
        self._stop_num = stop_num

    @classmethod
    def from_dict(cls, dikt) -> "Solution":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Solution of this Solution.  # noqa: E501
        :rtype: Solution
        """
        return util.deserialize_model(dikt, cls)

    @property
    def demand(self) -> Demand:
        """Gets the demand of this Solution.


        :return: The demand of this Solution.
        :rtype: Demand
        """
        return self._demand

    @demand.setter
    def demand(self, demand: Demand):
        """Sets the demand of this Solution.


        :param demand: The demand of this Solution.
        :type demand: Demand
        """

        self._demand = demand

    @property
    def cluster_id(self) -> int:
        """Gets the cluster_id of this Solution.


        :return: The cluster_id of this Solution.
        :rtype: int
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id: int):
        """Sets the cluster_id of this Solution.


        :param cluster_id: The cluster_id of this Solution.
        :type cluster_id: int
        """
        if cluster_id is None:
            raise ValueError(
                "Invalid value for `cluster_id`, must not be `None`"
            )  # noqa: E501

        self._cluster_id = cluster_id

    @property
    def vehicle_id(self) -> int:
        """Gets the vehicle_id of this Solution.


        :return: The vehicle_id of this Solution.
        :rtype: int
        """
        return self._vehicle_id

    @vehicle_id.setter
    def vehicle_id(self, vehicle_id: int):
        """Sets the vehicle_id of this Solution.


        :param vehicle_id: The vehicle_id of this Solution.
        :type vehicle_id: int
        """
        if vehicle_id is None:
            raise ValueError(
                "Invalid value for `vehicle_id`, must not be `None`"
            )  # noqa: E501

        self._vehicle_id = vehicle_id

    @property
    def stop_num(self) -> int:
        """Gets the stop_num of this Solution.


        :return: The stop_num of this Solution.
        :rtype: int
        """
        return self._stop_num

    @stop_num.setter
    def stop_num(self, stop_num: int):
        """Sets the stop_num of this Solution.


        :param stop_num: The stop_num of this Solution.
        :type stop_num: int
        """
        if stop_num is None:
            raise ValueError(
                "Invalid value for `stop_num`, must not be `None`"
            )  # noqa: E501

        self._stop_num = stop_num
