# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from app import util
from app.api.models.base_model_ import Model
from app.api.v0_1.models.demand import Demand  # noqa: F401,E501
from app.api.v0_1.models.origin import Origin  # noqa: F401,E501
from app.api.v0_1.models.unit import Unit  # noqa: F401,E501


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        origin: Origin = None,
        demands: List[Demand] = None,
        unit: Unit = None,
        vehicle_capacity: int = None,
        vehicle_definitions: List[int] = None,
    ):  # noqa: E501
        """Body - a model defined in Swagger

        :param origin: The origin of this Body.  # noqa: E501
        :type origin: Origin
        :param demands: The demands of this Body.  # noqa: E501
        :type demands: List[Demand]
        :param unit: The unit of this Body.  # noqa: E501
        :type unit: Unit
        :param vehicle_capacity: The vehicle_capacity of this Body.  # noqa: E501
        :type vehicle_capacity: int
        :param vehicle_definitions: The vehicle_definitions of this Body.  # noqa: E501
        :type vehicle_definitions: List[int]
        """
        self.swagger_types = {
            "origin": Origin,
            "demands": List[Demand],
            "unit": Unit,
            "vehicle_capacity": int,
            "vehicle_definitions": List[int],
        }

        self.attribute_map = {
            "origin": "origin",
            "demands": "demands",
            "unit": "unit",
            "vehicle_capacity": "vehicle_capacity",
            "vehicle_definitions": "vehicle_definitions",
        }
        self._origin = origin
        self._demands = demands
        self._unit = unit
        self._vehicle_capacity = vehicle_capacity
        self._vehicle_definitions = vehicle_definitions

    @classmethod
    def from_dict(cls, dikt) -> "Body":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def origin(self) -> Origin:
        """Gets the origin of this Body.


        :return: The origin of this Body.
        :rtype: Origin
        """
        return self._origin

    @origin.setter
    def origin(self, origin: Origin):
        """Sets the origin of this Body.


        :param origin: The origin of this Body.
        :type origin: Origin
        """
        if origin is None:
            raise ValueError(
                "Invalid value for `origin`, must not be `None`"
            )  # noqa: E501

        self._origin = origin

    @property
    def demands(self) -> List[Demand]:
        """Gets the demands of this Body.


        :return: The demands of this Body.
        :rtype: List[Demand]
        """
        return self._demands

    @demands.setter
    def demands(self, demands: List[Demand]):
        """Sets the demands of this Body.


        :param demands: The demands of this Body.
        :type demands: List[Demand]
        """
        if demands is None:
            raise ValueError(
                "Invalid value for `demands`, must not be `None`"
            )  # noqa: E501

        self._demands = demands

    @property
    def unit(self) -> Unit:
        """Gets the unit of this Body.


        :return: The unit of this Body.
        :rtype: Unit
        """
        return self._unit

    @unit.setter
    def unit(self, unit: Unit):
        """Sets the unit of this Body.


        :param unit: The unit of this Body.
        :type unit: Unit
        """
        if unit is None:
            raise ValueError(
                "Invalid value for `unit`, must not be `None`"
            )  # noqa: E501

        self._unit = unit

    @property
    def vehicle_capacity(self) -> int:
        """Gets the vehicle_capacity of this Body.


        :return: The vehicle_capacity of this Body.
        :rtype: int
        """
        return self._vehicle_capacity

    @vehicle_capacity.setter
    def vehicle_capacity(self, vehicle_capacity: int):
        """Sets the vehicle_capacity of this Body.


        :param vehicle_capacity: The vehicle_capacity of this Body.
        :type vehicle_capacity: int
        """
        if vehicle_capacity is None:
            raise ValueError(
                "Invalid value for `vehicle_capacity`, must not be `None`"
            )  # noqa: E501

        self._vehicle_capacity = vehicle_capacity

    @property
    def vehicle_definitions(self) -> List[int]:
        """Gets the vehicle_definitions of this Body.


        :return: The vehicle_definitions of this Body.
        :rtype: List[int]
        """
        return self._vehicle_definitions

    @vehicle_definitions.setter
    def vehicle_definitions(self, vehicle_definitions: List[int]):
        """Sets the vehicle_definitions of this Body.


        :param vehicle_definitions: The vehicle_definitions of this Body.
        :type vehicle_definitions: List[int]
        """

        self._vehicle_definitions = vehicle_definitions
