# coding: utf-8

from __future__ import absolute_import

import re  # noqa: F401,E501
from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from app import util
from app.api.models.base_model_ import Model
from app.api.models.demand import Demand  # noqa: F401,E501
from app.api.models.origin import Origin  # noqa: F401,E501
from app.api.models.unit import Unit  # noqa: F401,E501
from app.api.models.vehicle_capacity import VehicleCapacity  # noqa: F401,E501


class ProcedureRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        origin: Origin = None,
        demand: List[Demand] = None,
        unit: Unit = None,
        vehicle_capacity: VehicleCapacity = None,
        vehicle_definitions: List[VehicleCapacity] = None,
    ):  # noqa: E501
        """ProcedureRequest - a model defined in Swagger

        :param origin: The origin of this ProcedureRequest.  # noqa: E501
        :type origin: Origin
        :param demand: The demand of this ProcedureRequest.  # noqa: E501
        :type demand: List[Demand]
        :param unit: The unit of this ProcedureRequest.  # noqa: E501
        :type unit: Unit
        :param vehicle_capacity: The vehicle_capacity of this ProcedureRequest.  # noqa: E501
        :type vehicle_capacity: VehicleCapacity
        :param vehicle_definitions: The vehicle_definitions of this ProcedureRequest.  # noqa: E501
        :type vehicle_definitions: List[VehicleCapacity]
        """
        self.swagger_types = {
            "origin": Origin,
            "demand": List[Demand],
            "unit": Unit,
            "vehicle_capacity": VehicleCapacity,
            "vehicle_definitions": List[VehicleCapacity],
        }

        self.attribute_map = {
            "origin": "origin",
            "demand": "demand",
            "unit": "unit",
            "vehicle_capacity": "vehicle_capacity",
            "vehicle_definitions": "vehicle_definitions",
        }
        self._origin = origin
        self._demand = demand
        self._unit = unit
        self._vehicle_capacity = vehicle_capacity
        self._vehicle_definitions = vehicle_definitions

    @classmethod
    def from_dict(cls, dikt) -> "ProcedureRequest":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The procedureRequest of this ProcedureRequest.  # noqa: E501
        :rtype: ProcedureRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def origin(self) -> Origin:
        """Gets the origin of this ProcedureRequest.


        :return: The origin of this ProcedureRequest.
        :rtype: Origin
        """
        return self._origin

    @origin.setter
    def origin(self, origin: Origin):
        """Sets the origin of this ProcedureRequest.


        :param origin: The origin of this ProcedureRequest.
        :type origin: Origin
        """
        if origin is None:
            raise ValueError(
                "Invalid value for `origin`, must not be `None`"
            )  # noqa: E501

        self._origin = origin

    @property
    def demand(self) -> List[Demand]:
        """Gets the demand of this ProcedureRequest.


        :return: The demand of this ProcedureRequest.
        :rtype: List[Demand]
        """
        return self._demand

    @demand.setter
    def demand(self, demand: List[Demand]):
        """Sets the demand of this ProcedureRequest.


        :param demand: The demand of this ProcedureRequest.
        :type demand: List[Demand]
        """
        if demand is None:
            raise ValueError(
                "Invalid value for `demand`, must not be `None`"
            )  # noqa: E501

        self._demand = demand

    @property
    def unit(self) -> Unit:
        """Gets the unit of this ProcedureRequest.


        :return: The unit of this ProcedureRequest.
        :rtype: Unit
        """
        return self._unit

    @unit.setter
    def unit(self, unit: Unit):
        """Sets the unit of this ProcedureRequest.


        :param unit: The unit of this ProcedureRequest.
        :type unit: Unit
        """
        if unit is None:
            raise ValueError(
                "Invalid value for `unit`, must not be `None`"
            )  # noqa: E501

        self._unit = unit

    @property
    def vehicle_capacity(self) -> VehicleCapacity:
        """Gets the vehicle_capacity of this ProcedureRequest.


        :return: The vehicle_capacity of this ProcedureRequest.
        :rtype: VehicleCapacity
        """
        return self._vehicle_capacity

    @vehicle_capacity.setter
    def vehicle_capacity(self, vehicle_capacity: VehicleCapacity):
        """Sets the vehicle_capacity of this ProcedureRequest.


        :param vehicle_capacity: The vehicle_capacity of this ProcedureRequest.
        :type vehicle_capacity: VehicleCapacity
        """
        if vehicle_capacity is None:
            raise ValueError(
                "Invalid value for `vehicle_capacity`, must not be `None`"
            )  # noqa: E501

        self._vehicle_capacity = vehicle_capacity

    @property
    def vehicle_definitions(self) -> List[VehicleCapacity]:
        """Gets the vehicle_definitions of this ProcedureRequest.


        :return: The vehicle_definitions of this ProcedureRequest.
        :rtype: List[VehicleCapacity]
        """
        return self._vehicle_definitions

    @vehicle_definitions.setter
    def vehicle_definitions(self, vehicle_definitions: List[VehicleCapacity]):
        """Sets the vehicle_definitions of this ProcedureRequest.


        :param vehicle_definitions: The vehicle_definitions of this ProcedureRequest.
        :type vehicle_definitions: List[VehicleCapacity]
        """

        self._vehicle_definitions = vehicle_definitions
