"""added cluster field to demand table

Revision ID: aacb6a1c660d
Revises: 3e45f3944387
Create Date: 2019-09-26 09:03:27.806515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aacb6a1c660d'
down_revision = '3e45f3944387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand', sa.Column('cluster', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demand', 'cluster')
    # ### end Alembic commands ###
